[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
version = "0.1.2"
name = "source-fauna"
description = "Source implementation for fauna."
authors = [ "Airbyte <contact@airbyte.io>",]
license = "MIT"
readme = "README.md"
documentation = "https://docs.airbyte.com/integrations/sources/fauna"
homepage = "https://airbyte.com"
repository = "https://github.com/airbytehq/airbyte"
[[tool.poetry.packages]]
include = "source_fauna"

[tool.poetry.dependencies]
python = "3.10.12"
airbyte-cdk = "0.60.0"
faunadb = "4.2.0"

[tool.poetry.scripts]
source-fauna = "source_fauna.run:run"

[tool.poetry.group.dev.dependencies]
requests-mock = "^1.9.3"
pytest = "^6.1"
freezegun = "^1.4.0"
pytest-mock = "^3.6.1"
docker = "^5.0.0"
