[tool.poetry]
name = "airbyte"
version = "0.1.0"
description = "Airbyte open source connector code"
authors = ["Airbyte <contact@airbyte.io>"]

[tool.poetry.dependencies]
python = "~3.10"

[tool.poetry.group.dev.dependencies]
isort = "5.6.4"
black = "~22.3.0"
ruff = "^1"
[tool.ruff]
[tool.flake8]
# Rules to be determined
# Configuration details to be determined

[tool.coverage.report]
fail_under = 0
skip_empty = true
sort = "-cover"
omit = [
    ".venv/*",
    "main.py",
    "setup.py",
    "unit_tests/*",
    "integration_tests/*",
    "**/generated/*",
]




[tool.mypy]
platform = "linux"
exclude = "(build|integration_tests|unit_tests|generated)"

# Optionals
ignore_missing_imports = true

# Strictness
allow_untyped_globals = false
allow_redefinition = false
implicit_reexport = false
strict_equality = true

# Warnings
warn_unused_ignores = true
warn_no_return = true
warn_return_any = true
warn_redundant_casts = true
warn_unreachable = true

# Error output
show_column_numbers = true
show_error_context = true
show_error_codes = true
show_traceback = true
pretty = true
color_output = true
error_summary = true

[tool.pytest.ini_options]
minversion = "6.2.5"
addopts ="-r a --capture=no -vv --color=yes"