[tool.poetry]
name = "perf-tests"
version = "0.1.0"
description = ""
authors = ["Aaron Steers <aj@airbyte.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
airbyte = "^0.17.7"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
