[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
version = "1.0.3"
name = "source-microsoft-teams"
description = "Source implementation for Microsoft Teams."
authors = [ "Airbyte <contact@airbyte.io>",]
license = "MIT"
readme = "README.md"
documentation = "https://docs.airbyte.com/integrations/sources/microsoft-teams"
homepage = "https://airbyte.com"
repository = "https://github.com/airbytehq/airbyte"
[[tool.poetry.packages]]
include = "source_microsoft_teams"

[tool.poetry.dependencies]
python = "^3.9,<3.12"
requests = "==2.31.0"
msal = "==1.7.0"
backoff = "==2.2.1"
airbyte-cdk = "0.80.0"

[tool.poetry.scripts]
source-microsoft-teams = "source_microsoft_teams.run:run"

[tool.poetry.group.dev.dependencies]
pytest-mock = "^3.6.1"
requests-mock = "^1.9.3"
pytest = "^6.1"
