[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
version = "1.2.4"
name = "source-salesloft"
description = "Source implementation for Salesloft."
authors = [ "Airbyte <contact@airbyte.io>",]
license = "MIT"
readme = "README.md"
documentation = "https://docs.airbyte.com/integrations/sources/salesloft"
homepage = "https://airbyte.com"
repository = "https://github.com/airbytehq/airbyte"
[[tool.poetry.packages]]
include = "source_salesloft"

[tool.poetry.dependencies]
python = "^3.9,<3.12"
airbyte-cdk = "0.80.0"
pendulum = "==2.1.2"

[tool.poetry.scripts]
source-salesloft = "source_salesloft.run:run"

[tool.poetry.group.dev.dependencies]
pytest = "^6.1"
pytest-mock = "^3.6.1"
requests-mock = "^1.12.1"
