[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
version = "1.0.3"
name = "source-chartmogul"
description = "Source implementation for Chartmogul."
authors = [ "Titas Skrebe <titas@omnisend.com>",]
license = "MIT"
readme = "README.md"
documentation = "https://docs.airbyte.com/integrations/sources/chartmogul"
homepage = "https://airbyte.com"
repository = "https://github.com/airbytehq/airbyte"
[[tool.poetry.packages]]
include = "source_chartmogul"

[tool.poetry.dependencies]
python = "^3.9,<3.12"
airbyte-cdk = "==0.53.2"

[tool.poetry.scripts]
source-chartmogul = "source_chartmogul.run:run"

[tool.poetry.group.dev.dependencies]
requests-mock = "^1.12.1"
pytest-mock = "^3.6.1"
pytest = "^6.1"
