[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
version = "5.3.0"
name = "source-zenloop"
description = "Source implementation for Zenloop."
authors = [ "Airbyte <contact@airbyte.io>",]
license = "Elv2"
readme = "README.md"
documentation = "https://docs.airbyte.com/integrations/sources/zenloop"
homepage = "https://airbyte.com"
repository = "https://github.com/airbytehq/airbyte"
[[tool.poetry.packages]]
include = "source_zenloop"

[tool.poetry.dependencies]
python = "^3.9,<3.12"
pendulum = "==2.1.2"
airbyte-cdk = "^0"

[tool.poetry.scripts]
source-trello = "source_zenloop.run:run"

[tool.poetry.group.dev.dependencies]
requests-mock = "^1.11.0"
pytest = "^6.1"
freezegun = "==1.2.2"
pytest-mock = "^3.6.1"
