[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
version = "0.3.4"
name = "source-aha"
description = "Source implementation for Aha."
authors = [ "Airbyte <contact@airbyte.io>",]
license = "MIT"
readme = "README.md"
documentation = "https://docs.airbyte.com/integrations/sources/aha"
homepage = "https://airbyte.com"
repository = "https://github.com/airbytehq/airbyte"
[[tool.poetry.packages]]
include = "source_aha"

[tool.poetry.dependencies]
python = "^3.9,<3.12"
airbyte-cdk = "==0.39.2"

[tool.poetry.scripts]
source-aha = "source_aha.run:run"

[tool.poetry.group.dev.dependencies]
pytest = "^6.1"
pytest-mock = "^3.6.1"
requests-mock = "^1.9.3"
