[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
version = "4.9.2"
name = "source-s3"
description = "Source implementation for S3."
authors = [ "Airbyte <contact@airbyte.io>",]
license = "ELv2"
readme = "README.md"
documentation = "https://docs.airbyte.com/integrations/sources/s3"
homepage = "https://airbyte.com"
repository = "https://github.com/airbytehq/airbyte"
[[tool.poetry.packages]]
include = "source_s3"

[tool.poetry.dependencies]
python = "^3.10,<3.12"
pytz = "==2024.1"
wcmatch = "==8.4"
dill = "==0.3.4"
transformers = "4.38.2"
urllib3 = "<2"

[tool.poetry.dependencies.airbyte-cdk]
extras = ["file-based"]

# ==== This section below defines the version of the CDK to use. ====
# - If you want to build using a branch from the CDK repo, uncomment the git and branch lines.
# - To use a local (editable) version of the CDK, uncomment the path line.
# - CI will require you to switch to a published version of the CDK before merging.
# - After making changes to this section, run `poetry lock` to update the lock file.
# - The "--use-local-cdk" option is deprecated and no longer required.
# - The airbyte-ci CLI is compatible with branch-based and published versions of the CDK.

# ===== Use local (editable) version of the CDK ====
# path = "../../../../airbyte-python-cdk-test/"
# develop = true

# ===== Use development version of the CDK =========
git = "https://github.com/airbytehq/airbyte-python-cdk-test.git"
branch = "aj/feat/refactor-pendulum-and-date-utils"

# ===== Use published version of the CDK ===========
# version = "^5.7.4"

[tool.poetry.scripts]
source-s3 = "source_s3.run:run"

[tool.poetry.dependencies.smart-open]
extras = [ "s3",]
version = "==5.1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^6.1"
moto = "==4.2.14"
docker = "^7.0.0"
pytest-mock = "^3.6.1"
requests-mock = "^1.9.3"
pandas = "^2.0.3"
