name: Connector Ops CI - Check contractors review requirements

on:
  pull_request:
    types:
      - opened
      - pull_request_review
      - ready_for_review
      - reopened
      - synchronize
jobs:
  check-review-requirements:
    name: "Check if a review is required from Connector teams"
    runs-on: ubuntu-latest

    if: ${{ github.repository == 'airbytehq/airbyte' }}
    steps:
      - name: Check contributor team membership
        uses: tspascoal/get-user-teams-membership@v3
        id: actorTeams
        with:
          username: ${{ github.actor }}
      - if: ${{ (contains(steps.actorTeams.outputs.teams, 'community-contractor')) }}
        name: Check if the review requirements are met
        uses: Automattic/action-required-review@v3
        with:
          status: Required review
          request-reviews: true
          fail: true
          requirements: |
            - paths: unmatched
              teams:
                - connector-extensibility
                - gl-python
