name: Check for formatting errors
run-name: Check for formatting errors on ${{ github.ref }}
on:
  workflow_dispatch:

  push:
    branches:
      - master
  pull_request:

jobs:
  format-check:
    # IMPORTANT: This name must match the require check name on the branch protection settings
    name: "Check for formatting errors"
    runs-on: tooling-test-small
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1
      - name: Run airbyte-ci format check [MASTER]
        id: airbyte_ci_format_check_all_master
        if: github.ref == 'refs/heads/master'
        uses: ./.github/actions/run-airbyte-ci
        continue-on-error: true
        with:
          context: "master"
          dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN_2 }}
          subcommand: "format check all"

      - name: Run airbyte-ci format check [PULL REQUEST]
        id: airbyte_ci_format_check_all_pr
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/run-airbyte-ci
        continue-on-error: false
        with:
          context: "pull_request"
          dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN_2 }}
          subcommand: "format check all"

      - name: Run airbyte-ci format check [WORKFLOW DISPATCH]
        id: airbyte_ci_format_check_all_manual
        if: github.event_name == 'workflow_dispatch'
        uses: ./.github/actions/run-airbyte-ci
        continue-on-error: false
        with:
          context: "manual"
          dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN_2 }}
          subcommand: "format check all"

      - name: Match GitHub User to Slack User [MASTER]
        if: github.ref == 'refs/heads/master'
        id: match-github-to-slack-user
        uses: ./.github/actions/match-github-to-slack-user
        env:
          AIRBYTE_TEAM_BOT_SLACK_TOKEN: ${{ secrets.SLACK_AIRBYTE_TEAM_READ_USERS }}
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Format Failure on Master Slack Channel [MASTER]
        if: steps.airbyte_ci_format_check_all.outcome == 'failure' && github.ref == 'refs/heads/master'
        uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
        with:
          args: >-
            {\"channel\":\"C03BEADRPNY\", \"blocks\":[
            {\"type\":\"divider\"},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Formatting is broken on master! :bangbang: \n\n\"}},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"_merged by_: *${{ github.actor }}* \n\"}},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<@${{ steps.match-github-to-slack-user.outputs.slack_user_ids }}> \n\"}},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\" :octavia-shocked: <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|View Action Run> :octavia-shocked: \n\"}},
            {\"type\":\"divider\"}]}
