name: Fix formatting on a branch
run-name: Fix formatting on ${{ github.ref }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel any previous runs on the same branch if they are still in progress
  cancel-in-progress: true

on:
  workflow_dispatch:
jobs:
  format-fix:
    name: "Run airbyte-ci format fix all"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Run airbyte-ci format fix all
        uses: ./.github/actions/run-airbyte-ci
        continue-on-error: true
        with:
          context: "manual"
          subcommand: "format fix all"

      # This is helpful in the case that we change a previously committed generated file to be ignored by git.
      - name: Remove any files that have been gitignored
        run: git ls-files -i -c --exclude-from=.gitignore | xargs -r git rm --cached

      - name: Commit Formatting Changes (PR)
        uses: stefanzweifel/git-auto-commit-action@v5
        # Don't commit if we're on master
        if: github.ref != 'refs/heads/master'
        with:
          commit_message: "chore: format code"
          commit_user_name: Octavia Squidington III
          commit_user_email: octavia-squidington-iii@users.noreply.github.com
